---
title: "R Day 2"
author: "JLewyckyj"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
here::here("data", "gapminder5.csv")

gapminder <- read.csv(here::here("data", "gapminder5.csv"))

#Convert factors into characters

gapminder$country <- as.character(gapminder$country)
gapminder$continent <- as.character(gapminder$continent)
```

```{r}
for (i in 1:nrow(gapminder)) {
  gapminder[i, "gdp"] <- gapminder[i, "pop"] * gapminder[i, "gdpPercap"]
}

for (i in 1:nrow(gapminder)) {
  gapminder[i, "log_gdpPercap"] <- log(gapminder[i, "gdpPercap"])
  gapminder[i, "log_pop"] <- log(gapminder[i, "pop"])
}
```

```{r}
years <- unique(gapminder$year)

for (i in years) {
  mean_le <- mean(gapminder$lifeExp[gapminder$year == i], na.rm=T)
  print(paste0(i, ": ", mean_le))
}
```

```{r}
conts <- unique(gapminder$continent)

for (i in conts) {
  mean_le_cont <- mean(gapminder$lifeExp[gapminder$continent == i], na.rm=T)
  print(paste0(i, ": ", mean_le_cont))
}
```

```{r}
for (i in conts) {
  print(paste0("Continent: ", i))
  for (j in years) {
    mean_le <- mean(gapminder$lifeExp[gapminder$continent == i & gapminder$year == j], na.rm=T)
    print(paste0(j, ": ", mean_le))
  }
}
```

```{r}
for (i in conts) {
  print(paste0("Continent: ", i))
  for (j in years) {
    sd_le <- sd(gapminder$lifeExp[gapminder$continent == i & gapminder$year == j], na.rm=T)
    print(paste0(j, ": ", sd_le))
  }
}
```

```{r}
vars <- gapminder[, c("lifeExp", "pop", "gdpPercap")]
apply(vars, 2, mean)

lapply(gapminder, mean)

sapply(years, function(x) mean(gapminder$lifeExp[gapminder$year == x]))
```

```{r}
i <- 1952 #define iterator

while (i < 1987) {
  sd_le <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ": ", sd_le))
  i <- i + 5 #increase interator by interval between years
}
```

```{r}
i <-  1987 # define the iterator

while (i <= 2002) {
  sd_le <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ": ", sd_le)
        )
  i <- i + 5 # increase the iterator by the interval between years
}
```

```{r}
random_year <- sample(years, 1)

random_year

if (random_year > 1977) {
  print(random_year)
}
```

```{r}
threshold <- 70

for(i in unique(gapminder$continent)) {
  tmp <- mean(gapminder$lifeExp[gapminder$continent==i])
  
  if (tmp < threshold) {
    print(paste("Mean Life Expectancy in", i, "is less than", threshold))
  } else {
    print(paste("Mean Life Expectancy in", i, "is greater than", threshold))
  }
}
```

```{r}
for(i in unique(gapminder$year)) {
  if (i >= 1987) {
  meanpop <- mean(gapminder$pop[gapminder$year==i])
  print(paste(i, ": ", meanpop))
  } else {
    print(paste(i, ": nah"))
  }
}
```

```{r}
report_stats <- function(df, variable, continent) {
  var <- df[[variable]][df$continent == continent]
  mean <- mean(var)
  med <- median(var)
  min <- min(var)
  max <- max(var)
  cat("Continent:", continent,
      "\n Mean Life Expectancy:", mean,
      "\n Median Life Expectancy:", med,
      "\n Min Life Expectancy:", min,
      "\n Max Life Expectancy:", max)
}

report_stats(gapminder, "lifeExp", "Americas")
```

